"""users table

Revision ID: 5b708c950563
Revises: 
Create Date: 2019-07-29 19:36:46.690797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b708c950563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapper_name'), 'rapper', ['name'], unique=True)
    op.create_table('signed_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rapper_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signed_up_rapper_id'), 'signed_up', ['rapper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signed_up_rapper_id'), table_name='signed_up')
    op.drop_table('signed_up')
    op.drop_index(op.f('ix_rapper_name'), table_name='rapper')
    op.drop_table('rapper')
    # ### end Alembic commands ###
