"""empty message

Revision ID: f4e6a3b6380b
Revises: 
Create Date: 2019-07-06 22:57:48.266470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e6a3b6380b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rapper_name'), 'rapper', ['name'], unique=True)
    op.create_table('signed_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rapper_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signed_up_rapper_id'), 'signed_up', ['rapper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signed_up_rapper_id'), table_name='signed_up')
    op.drop_table('signed_up')
    op.drop_index(op.f('ix_rapper_name'), table_name='rapper')
    op.drop_table('rapper')
    # ### end Alembic commands ###
